timezone: America/Denver
# Dependencies
markdown:       kramdown
redcarpet:
    extensions: ['smart']

highlighter:         rouge
fenced_code_blocks:  true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            Computing Thoughts
tagline:          Artemiadis's Programming Blog
url:              http://miracle-jr.github.io/
paginate:            5
baseurl:          /

# About/contact
author:
  name:           Artemiadis
  url:            http://miracle-jr.github.io/
  email:          geniuses2000@gmail.com

